### ISSUE TITLE
Invalid Output FIle

### ISSUE THREAD

**Issue by alexmbird** [dcherednik/atracdenc#1]
Hello there,

First of all - many thanks for this project.  I am hopeful of using it to transcode audio into 292kbit ATRAC and use the [linux-minidisc](https://wiki.physik.fu-berlin.de/linux-minidisc/doku.php?id=start) to upload to a NetMD [recorder](http://www.minidisc.org/part_Sony_MZ-N510.html).

To build it (on OSX) I had to add the `-DCMAKE_CXX_FLAGS=-std=c++11` flag to cmake.   It'd be helpful to others to add that to the readme.

Now I try to encode a file.  Here's some info about my setup:

```bash
$ ffmpeg -version
ffmpeg version 3.1.3 Copyright (c) 2000-2016 the FFmpeg developers
built with Apple LLVM version 7.3.0 (clang-703.0.31)
configuration: --prefix=/usr/local/Cellar/ffmpeg/3.1.3 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libxvid --enable-libfaac --enable-libfdk-aac --enable-libx265 --disable-lzma --enable-nonfree --enable-vda
libavutil      55. 28.100 / 55. 28.100
libavcodec     57. 48.101 / 57. 48.101
libavformat    57. 41.100 / 57. 41.100
libavdevice    57.  0.101 / 57.  0.101
libavfilter     6. 47.100 /  6. 47.100
libavresample   3.  0.  0 /  3.  0.  0
libswscale      4.  1.100 /  4.  1.100
libswresample   2.  1.100 /  2.  1.100
libpostproc    54.  0.100 / 54.  0.100

$ brew info libsndfile
libsndfile: stable 1.0.26 (bottled)

$ ffmpeg -i input.wav
...
Guessed Channel Layout for Input Stream #0.0 : stereo
Input #0, wav, from 'input.wav':
..
  Duration: 00:07:27.67, bitrate: 1411 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 2 channels, s16, 1411 kb/s
```
Here goes the encode...

```bash
$ ./atracdenc --encode -i input.wav -o output.atrac
Input file: input.wav
 Channels: 2
 SampleRate: 44100
 TotalSamples: 0x7fff504b9658
/  99% done
Done
```

How's that file?

```bash
$ file output.atrac
output.atrac: Applesoft BASIC program data
```

Hmmm, 'file' is wrong.  How about ffmpeg?

```bash
$ ffmpeg -acodec atrac1 -i output.atrac
...
[aac @ 0x7ff9b1002600] Format aac detected only with low score of 1, misdetection possible!
```

But you said in the readme it might misdetect the file.  I'll try forcing atrac1...

```bash
$ ffmpeg -acodec atrac1  -i output.atrac
...
[aac @ 0x7ff713000000] Format aac detected only with low score of 1, misdetection possible!
[atrac1 @ 0x7ff713000c00] Unsupported number of channels: 0
[aac @ 0x7ff713000000] Failed to open codec in av_find_stream_info
[atrac1 @ 0x7ff713000c00] Unsupported number of channels: 3
[aac @ 0x7ff713000000] Estimating duration from bitrate, this may be inaccurate
Guessed Channel Layout for Input Stream #0.0 : 4.0
Input #0, aac, from 'output.atrac':
  Duration: 00:05:51.64, bitrate: 372 kb/s
    Stream #0:0: Audio: atrac1, 48000 Hz, 4 channels, fltp, 372 kb/s
At least one output file must be specified
```

4 channels @ 48khz?  This is not my audio :(

What about sndfile?

```bash
$ sndfile-info output.atrac
Error : Not able to open input file output.atrac.
File : output.atrac
Length : 16351488

File contains data in an unknown format.
```

Can you tell me what I'm doing wrong?

**Comment by dcherednik** [comment]
Hello!
Thanks for trying to use it ))
About compilation, thanks for report. I found the problem, I just want to check gcc compilation before commit.

About file format. Aea is not standard container for media file, this is why file util, or sndfile show something wrong. Try to rename file to output.aea, ffmpeg did not detect container in your case. mplayer, vlc also should be able to play it, but file extensions also makes sense. If it does not help  please show `hexdump -C output.aea | head`

In my case worked file:
```
00000000  00 08 00 00 74 65 73 74  00 00 00 00 00 00 00 00  |....test........|
00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000100  00 00 00 00 38 36 01 00  02 00 00 00 00 00 00 00  |....86..........|
00000110  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
000008d0  00 00 00 00 00 e0 22 22  22 22 22 22 22 22 22 33  |......"""""""""3|
000008e0  33 32 12 22 12 22 23 32  11 21 22 22 00 01 00 10  |32."."#2.!""....|
000008f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000900  20 03 00 41 05 00 61 46  00 51 86 00 32 46 28 c2  | ..A..aF.Q..2F(.|
```

**Comment by alexmbird** [comment]
Hello there,

Thanks for responding so quickly.  You are right: my output file is fine, a valid ATRAC file at 292kbit, which is just what I needed.  It plays well in VLC.  This is a huge step forward in getting these beautiful old NetMD recorders to work on a modern OS :)  Later this weekend I'll hack linux-minidisc to support 292kbit ATRAC and try to upload the data to a disc.

Now, you asked for a sample of ATRAC from a MiniDisc.  Sony designed these things so you could write your ATRAC data to a disc but never extract it over USB, only play it from the device.  The only exception was the last player Sony made, the [MZ-RH1](http://www.minidisc.org/part_Sony_MZ-RH1.html).  Sadly I don't have one but I'll try to find some sample data for you - perhaps somebody in the MiniDisc community has an RH1 and can help us.

**Comment by alexmbird** [comment]
I've found some examples [here](https://wiki.physik.fu-berlin.de/linux-minidisc/doku.php?id=himddiskformat) of the newer HiMD format, but I think some of the example images contain ATRAC3 tracks.  I'll see if I can find something better.

**Comment by alexmbird** [comment]
Another update: I've tried to upload a 292kbit file to a NetMD recorder and found I cannot.  The file is fine, but it turns out Sony designed the hardware never to accept uploads of high-bitrate files.  My dream of encoding better ATRAC for these old players is dead.

Thank you for your help and best of luck with this great project.

**Comment by dcherednik** [comment]
Thanks! Yes it is not easy to upload or download atrac1 files.
Did you try to upload atrac3? May be you can use atrac3 with non standard bitrate?

**Comment by alexmbird** [comment]
There are already a few methods to generate and transfer audio at lower bitrates: Sony's (terrible) SonicStage software, and a copy of the win32 ATRAC codec is floating around which can do LP and LP2.  But there was no way to encode at 292kbit and I assumed this would be the only barrier to encoding my own MiniDiscs.  Sadly I was wrong; Sony tried hard to stop you pressing your own high-quality discs.

Looking at http://www.minidisc.org/mdlpfaq.html - the amount of padding in the on-disk format makes me think the players have very precise expectations of bitrate.  They only understand data at 292kbps (original SP), 132kbps (LP2) and 66kbps (LP4) so I worry feeding my hardware anything else would be bad for it.
