### ISSUE TITLE
Can't succeed in compiling

### ISSUE THREAD

**Issue by YugoDago87** [dcherednik/atracdenc#10]
Hello !

First of all I want to thank you for this great idea of ATRAC encoder.

I will start with one important information : **I am a big noob !!!** Then sorry if I am asking stupid questions.

When I follow your instruction and try to compile your software, I have error message that I don't understand after the **cmake ../** command

_CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBSNDFILE_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/yugo/Documents/atracdenc-master/src
   used as include directory in directory /home/yugo/Documents/atracdenc-master/src
   used as include directory in directory /home/yugo/Documents/atracdenc-master/src
   used as include directory in directory /home/yugo/Documents/atracdenc-master/src
   used as include directory in directory /home/yugo/Documents/atracdenc-master/src
   used as include directory in directory /home/yugo/Documents/atracdenc-master/src
   used as include directory in directory /home/yugo/Documents/atracdenc-master/src
   used as include directory in directory /home/yugo/Documents/atracdenc-master/src
SNDFILE_LIBRARY (ADVANCED)
    linked by target "atracdenc" in directory /home/yugo/Documents/atracdenc-master/src_

I am using linux mint.

Could you please help ? I attache both output files.

Thank you a lot.
Regards.

[CMakeError.log](https://github.com/dcherednik/atracdenc/files/4376572/CMakeError.log)
[CMakeOutput.log](https://github.com/dcherednik/atracdenc/files/4376573/CMakeOutput.log)

**Comment by dcherednik** [comment]
Hi
Did you have libsndfile installed? I have no mint on my computers, but mint is ubuntu based so try this
`sudo apt-get install libsndfile1 libsndfile1-dev`

**Comment by YugoDago87** [comment]
Thank you so mush, you were right this is working, however I have another error at the _Make_ step.
I am sorry for my lack of knowledge... A copy of my result is attached.

[Result.log](https://github.com/dcherednik/atracdenc/files/4383947/Result.log)

**Comment by dcherednik** [comment]
It was my error, thank you for the report, i have fixed it in 3a8442c829. Try to update and compile again.

**Comment by YugoDago87** [comment]
Hello,

Thank you for your prompt reply ! I used the last version and I get a new type of error. Attached is the result.
[report.log](https://github.com/dcherednik/atracdenc/files/4392547/report.log)

**Comment by dcherednik** [comment]
Please update and try one more time. I think I fix it in 7b77cc31. For some reason the linkage was successful on debian and freebsd where I checked this project, but failed on mint. Thank you.

**Comment by gavinbenda** [comment]
I'm getting the same error on Ubuntu

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBSNDFILE_INCLUDE_DIR (ADVANCED)
```

**Comment by dcherednik** [comment]
Do you have libsndfile and libsndfile-dev installed?

I recheck. Current trunk compiled successful on ubuntu, debian, mint, and freebsd.

> I'm getting the same error on Ubuntu
> 
> ```
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> LIBSNDFILE_INCLUDE_DIR (ADVANCED)
> ```

**Comment by gavinbenda** [comment]
That worked thanks! Maybe the same issue for @YugoDago87 ?

**Comment by YugoDago87** [comment]
Hello !
Thank you very mush now it's work for me ! 

I have few other question :
How do I use it ? Do I need to cd in the _build_ or _test_ directory ? When I try after reboot it say _./atracdenc_ bash does not exist
Is it possible to encore multiples files ?

And finally, which version of the ATRAC encoder did you make, I mean 4.5 ? DSP Type R ?

Thank you again for all your work !

**Comment by gavinbenda** [comment]
@YugoDago87 off topic - but if you're looking for a "package" to transcode and send atrac files which uses atracdenc - my app might make your life easy https://github.com/gavinbenda/platinum-md/

**Comment by YugoDago87** [comment]
@gavinbenda Hello,
Thank you for this, be sure I will test it ! :-)

**Comment by dcherednik** [comment]
@YugoDago87 Hello.
You should run ./atracdenc from directory where linker place the binary. It should be build/src
No need to reboot) Just cd to build/src
Or you can try to use GUI, as @gavinbenda suggested.
