### ISSUE TITLE
Encoder hangs while converting wav file

### ISSUE THREAD

**Issue by cybercase** [dcherednik/atracdenc#16]
Hello @dcherednik and thanks for your great work.

I've been using your precious encoder in one of my side project for a while (here's the link if you're curious: https://github.com/cybercase/webminidisc). One of my users reported that the atracdenc encoder is hanging during conversion; see https://github.com/cybercase/webminidisc/issues/24

After a quick investigation I've been able to reproduce and debug the issue. Basically the encoder ends up into an infinite loop here https://github.com/dcherednik/atracdenc/blob/40d971c988fd9ccfb82cc6aaacc57ca1ad477d52/src/atrac/atrac3_bitstream.cpp#L196

Using the debugger I see that at every iteration, the loop ends up into line 218 and the `minShift` variable is always updated with the same value.
e.g. if `maxShift` = 15.00, `minShift` = 15.02, `shift` = 15.01 then the new `minShift = shift + 0.01` value will be equal to the previous, at every iteration. Note that `maxShift` can actually be less than `minShift`... I'm not sure if this is the problem.

To reproduce the issue you can use this wav file: https://www.dropbox.com/s/94jwklx6xi2uqgh/broken.wav?dl=0
and this command line `atracdenc -e atrac3 -i broken.wav -o broken.oma --bitrate 64`

I would have fixed the problem myself if I knew more about the code and the algorithm. However, just let me know if there's anything I can do to help.

**Comment by dcherednik** [comment]
Hi. Sorry for delay, for some reason I missed github notifications.

Thank you for report and file, I think i fixed the issue in 62ced878b526d49e5ef6ad42ca2eb7efc874867a
Actually current bit allocation algorithm is quite poor and the good idea to rewrite it.

**Comment by cybercase** [comment]
I wish I had some experience in this field to be of some help. However, now it works perfectly, thanks!
