### ISSUE TITLE
Assert failure on ATRAC3 encode

### ISSUE THREAD

**Issue by jiceher** [dcherednik/atracdenc#3]
Hi,

I try to use ATRAC3 encode from 44Khz 16bit WAV file. I first encode successfully using ATRAC1 but I got an assertion on line 426 of atrac/atrac3_bitstream.cpp:
`
assert(channel.size() <= Params.FrameSz/2);
`
with channel.size() is equal to 781 and Params.FrameSz equal to 96.

More, where can I found the specification of the algorithm implemented in order to help?

thanks

**Comment by dcherednik** [comment]
Try to add --bitrate=128 option.
ATRAC3 is uncompleted. There are a few feature should be implemented to get proper quality. For example, ATRAC3 codec has no long/short window switch, it uses gain control instead. This feature looks simple, but you will find some problems when try to implement it considering bitstream limitation. So right now gain control disabled and should be reimplemented. 

There are no specifications, some information you can find on minidisc.org, but for me most helpful was reading atrac3 decoder ffmpeg code.

Feel free to ask if you have some questions.
Thanks.

**Comment by jiceher** [comment]
Yes, thanks it works.

**Comment by dcherednik** [comment]
I set default to LP2 97a9667b1442624b41ad14bc3712e759205ecd8
