### ISSUE TITLE
Build Windows exe

### ISSUE THREAD

**Issue by Invictaz** [dcherednik/atracdenc#6]
Hi, 

as of https://github.com/dcherednik/atracdenc/commit/ed9629395ce9696164c1d617d573a47982e82169

there is MS Windows support. Can your provide an exe file that we can use to encode .aea?

Thanks

**Comment by dcherednik** [comment]
Hi.

I have made prerelease. Windows binary can be downloaded here https://github.com/dcherednik/atracdenc/releases/download/0.0.1/atracdenc-x86-rel-trunk-20190619.zip
Tested on windows 7,should work for any newer version.

Thanks.

**Comment by Invictaz** [comment]
@dcherednik Great work 

Going to post some other requests as well.
