### ISSUE TITLE
WAV container instead of AEA

### ISSUE THREAD

**Issue by Invictaz** [dcherednik/atracdenc#8]
According to 

![image](https://user-images.githubusercontent.com/20338545/69998563-e2859f00-1556-11ea-9e77-bb54b5ba62ab.png)

Uploading of SP tracks (ATRAC1) to Minidisc devices over NetMD is possible. @brenthuisman and @vuori use this in the Linux-Minidisc builds 

However your converter generates .aea extensions instead of WAV containers. Can you implement also WAV extensions? So input is WAV PCM and output is WAV ATRAC1. The result can be given a different filename. I presume it's more than just renaming the .aea extension.

**Comment by dcherednik** [comment]
Are you sure wav container can be used for ATRAC1? I quickly read python script, but did not find code to read wav and send payload to md device for SP mode. There is a code to save SP payload as aea on a computer or LP2/LP4 as wav, but LP2/LP4 is atrac3 so it is different codec.
FFmpeg also supports aea only for ATRAC1.

**Comment by Invictaz** [comment]
@dcherednik According to 

https://www.minidisc.org/NetMD_faq.html#_q83

AEA Data is encoded to in PCM then encrypted then transferred. But that FAQ is really old.

The script i'm referring to is 

https://raw.githubusercontent.com/vuori/linux-minidisc/master/netmd/upload.py

It seems that it can take both .aea and wav

**Comment by dcherednik** [comment]
`
if codec == libnetmd.ENCODING_SP:
            md_iface.saveTrackToStream(track, aeafile,events=aeaUploadEvents(aeafile, channels, title))
        else:
            md_iface.saveTrackToStream(track, aeafile,events=wavUploadEvents(aeafile))

`
so it uses aea for SP mode

**Comment by Invictaz** [comment]
Ok fine.
